### ISSUE TITLE
report 의미있게 바꾸기

### ISSUE THREAD

**Issue by TintypeMolly** [skyser2003/Sojong-2016-1#2]
## 삭제

AllSpreadReport 빼고 기존 레포트들은 다 쓸모없으니까 지우셈.

## 새로만들기

Hierarchical Clustering 알고리즘일 경우에는 현재 그래프의 node들과 edge의 weight들 전체를 기록하고,
hierarchy 별로 그룹이 어떻게 만들어지고 있는지를 report하게 만들기.
얘는 AllSpreadReport처럼 야매 json 쓰지 말고 완전히 legit한 형태의 json으로 뱉길 바람.

**Comment by Perlmint** [comment]
일단 중복 제거함

**Comment by Perlmint** [comment]
trial별로 분리된 report작성함
